### ISSUE TITLE
macOS arm64 test failure: cconv_array.t

### ISSUE THREAD

**Issue by shoe42** [terralang/terra#604] opened 2022-08-23 17:17 UTC
The `cconv_array.t` test fails on macOS arm64 (M1). macOS 12.5, using system clang and Homebrew LLVM 13. Trimmed output:
```llvm
$ ../build/bin/terra cconv_array.t
running test for int8[0]
running test for int8[1]
running test for int8[2]
running test for int8[3]
running test for int8[4]
running test for int8[5]
running test for int8[6]
running test for int8[7]
running test for int8[8]
running test for int8[9]
cconv_array.t:53: NYI: cannot call this C function (yet)
stack traceback:
	[C]: in function 'caller'
	cconv_array.t:53: in function 'run_test_case'
	cconv_array.t:64: in main chunk
```

**Comment by elliottslaughter** [comment] 2022-08-23 18:35
I suspect this is a Lua bug.

Can you please help me with this test?

`bug604.c`:

```c
#include <stdint.h>

int8_t f(int8_t x0, int8_t x1, int8_t x2, int8_t x3, int8_t x4, int8_t x5, int8_t x6, int8_t x7, int8_t x8, int8_t x9) {
  return x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9;
}
```

`bug604.t`:

```terra
local c = terralib.includecstring [[
#include <stdint.h>

int8_t f(int8_t x0, int8_t x1, int8_t x2, int8_t x3, int8_t x4, int8_t x5, int8_t x6, int8_t x7, int8_t x8, int8_t x9);
]]

terralib.linklibrary("libbug604.dylib")

print(c.f(0, 1, 2, 3, 4, 5, 6, 7, 8, 9))
```

`bug604.lua`:

```lua
local ffi = require("ffi")

ffi.cdef [[
int8_t f(int8_t x0, int8_t x1, int8_t x2, int8_t x3, int8_t x4, int8_t x5, int8_t x6, int8_t x7, int8_t x8, int8_t x9);
]]

local c = ffi.load("libbug604")

print(c.f(0, 1, 2, 3, 4, 5, 6, 7, 8, 9))
```

Then run:

```
clang bug604.c -o libbug604.dylib -shared -Wall
./build/bin/terra bug604.t
./build/bin/terra bug604.lua
```

It should print `45` with each of the last two commands, but I suspect it will fail with both.

**Comment by elliottslaughter** [comment] 2022-08-23 19:55
Ok, definitely a LuaJIT bug. I'll file an issue shortly. It might help to have:

 1. `uname -a`
 2. XCode version (whether full XCode app or command line tools, output of `clang --version`)
 3. macOS version

**Comment by elliottslaughter** [comment] 2022-08-23 20:47
Upstream issue submitted: https://github.com/LuaJIT/LuaJIT/issues/888

**Comment by elliottslaughter** [comment] 2022-08-24 15:51
The upstream issue was closed as a duplicate of https://github.com/LuaJIT/LuaJIT/issues/205, which has been open for six years with no indication of being a priority. I think at this point the best we can do is modify the bounds on this test so that we stick to what works.

**Comment by elliottslaughter** [comment] 2022-09-02 19:03
@shoe42 Is this still failing? What does the output look like on `master` now?

**Comment by elliottslaughter** [comment] 2022-09-02 19:06
Sigh. Ok, if you take out `int16` for a moment, does it fail on `int32` too? I can work around this but would like to know what types I'll need to do so for.

**Comment by elliottslaughter** [comment] 2022-09-02 19:10
Thanks. I'll make a new workaround.

**Comment by elliottslaughter** [comment] 2022-09-02 19:20
Can you try running the version of `cconv_array.t` in #611 and let me know if it works this time?

**Comment by elliottslaughter** [comment] 2022-09-05 21:54
Thanks! Merged. I think all tests should pass in `master` now.

**Comment by elliottslaughter** [comment] 2022-09-06 17:42
@shoe42 if you'd like to do one last check, I can get a release rolling.

**Comment by elliottslaughter** [comment] 2022-09-06 18:15
Thanks, will release here shortly.

**Closed by elliottslaughter** 2022-09-06 18:15 UTC

**Comment by elliottslaughter** [comment] 2023-08-30 19:45
Just FYI: as of #642 I have pulled in an updated LuaJIT that fixes the root cause, and with that, we can now run the full `cconv_array.t` test again.
