### ISSUE TITLE
Unable to build terra on Centos 8

### ISSUE THREAD

**Issue by Nischay-Pro** [terralang/terra#428] opened 2020-01-22 11:35 UTC
Hi,

I'm trying to build Terra on Centos 8. I've installed gcc 9.2.0 and clang 9.0.0 and ran the usual build steps.

I got a lot of undefined reference errors

Here is the attached build log. **Warning the log is around 6.9 MB**
https://filebin.net/r43u393e1ni7ultc/log?t=wj33et3g

I've tried using clang 6.0.1 and got the same issue.
Any idea why this is happening?

**Comment by elliottslaughter** [comment] 2020-01-22 18:44
Can you give us some steps for reproducing? E.g. what packages did you install, did you use SCL, etc. Ideally such that someone would be able to `docker run -ti centos:8` and get to a reproducing state.

Looking at the logs, my initial reaction is all the missing stuff seems to be in the C++ standard library. So it could be a case of linking against a different libc++/libstdc++ from what LLVM was built with, or something similar.

**Comment by Nischay-Pro** [comment] 2020-01-23 06:03
I installed GCC 8.2.1 available in the Base repo of Centos. Installed [spack](https://github.com/spack/spack/) and used GCC 8.2.1 to build GCC 9.2.0. 

Used GCC 9.2.0 to build LLVM 9.0.0 and then ran the build steps using GCC 9.2.0 and LLVM 9.0.0.

**Comment by Nischay-Pro** [comment] 2020-01-23 09:11
Okay. So for some reason my GCC 8.2.1 environment was leaking into my GCC 9.2.0 environment. I added the absolute paths to the following CMAKE flags and it worked.
DCMAKE_CXX_COMPILER=g++ 
DCMAKE_C_COMPILER=gcc

**Comment by elliottslaughter** [comment] 2020-01-23 17:03
Ok, cool. I'm going to close this issue but please feel free to open a new one if you have any further issues.

**Closed by elliottslaughter** 2020-01-23 17:03 UTC
