### ISSUE TITLE
macOS arm64 test failure: atomicrmw.t

### ISSUE THREAD

**Issue by shoe42** [terralang/terra#603] opened 2022-08-23 17:10 UTC
The `atomicrmw.t` test fails on macOS arm64 (M1). macOS 12.5, using system clang and Homebrew LLVM 13. Trimmed output:
```llvm
$ ../build/bin/terra atomicrmw.t
atomicrmw test settings: synscope true, align true, fadd true
atomicrmw.t:11:         terra atomic_add(x : &int32,y : int32,z : int32,w : int32,u : int32) : {}
atomicrmw.t:12:             atomicrmw("add", x, y, { syncscope = "", ordering = "seq_cst", align = native, isvolatile = false })
atomicrmw.t:13:             atomicrmw("add", x, z, { syncscope = "", ordering = "acq_rel", align = native, isvolatile = false })
atomicrmw.t:14:             fence({ syncscope = "", ordering = "release" })
atomicrmw.t:18:             atomicrmw("add", x, w, { syncscope = "singlethread", ordering = "monotonic", align = 16, isvolatile = false })
atomicrmw.t:30:             fence({ syncscope = "", ordering = "acquire" })
atomicrmw.t:31:             atomicrmw("add", x, u, { syncscope = "", ordering = "monotonic", align = native, isvolatile = true })
atomicrmw.t:11:         end
definition 	{&int32,int32,int32,int32,int32} -> {}
define dso_local void @"$atomic_add"(i32* %0, i32 %1, i32 %2, i32 %3, i32 %4) {
entry:
  %5 = atomicrmw add i32* %0, i32 %1 seq_cst, align 4
  %6 = atomicrmw add i32* %0, i32 %2 acq_rel, align 4
  fence release
  %7 = atomicrmw add i32* %0, i32 %3 syncscope("singlethread") monotonic, align 16
  fence acquire
  %8 = atomicrmw volatile add i32* %0, i32 %4 monotonic, align 4
  ret void
}
assembly for function at address 0x109530000
0x109530000(+0):		ldaxr	w8, [x0]
0x109530004(+4):		add	w8, w8, w1
0x109530008(+8):		stlxr	w9, w8, [x0]
0x10953000c(+12):		cbnz	w9, #-12
0x109530010(+16):		ldaxr	w8, [x0]
0x109530014(+20):		add	w8, w8, w2
0x109530018(+24):		stlxr	w9, w8, [x0]
0x10953001c(+28):		cbnz	w9, #-12
0x109530020(+32):		dmb	ish
0x109530024(+36):		ldxr	w8, [x0]
0x109530028(+40):		add	w8, w8, w3
0x10953002c(+44):		stxr	w9, w8, [x0]
0x109530030(+48):		cbnz	w9, #-12
0x109530034(+52):		dmb	ishld
0x109530038(+56):		ldxr	w8, [x0]
0x10953003c(+60):		add	w8, w8, w4
0x109530040(+64):		stxr	w9, w8, [x0]
0x109530044(+68):		cbnz	w9, #-12
0x109530048(+72):		ret
54321
atomicrmw.t:69:         terra atomic_add_and_return(x : &int32,y : int32) : int32
atomicrmw.t:70:             return atomicrmw("add", x, y, { syncscope = "", ordering = "acq_rel", align = native, isvolatile = false })
atomicrmw.t:69:         end
definition 	{&int32,int32} -> int32
define dso_local i32 @"$atomic_add_and_return"(i32* %0, i32 %1) {
entry:
  %2 = atomicrmw add i32* %0, i32 %1 acq_rel, align 4
  ret i32 %2
}
assembly for function at address 0x1096b0000
0x1096b0000(+0):		ldaxr	w8, [x0]
0x1096b0004(+4):		add	w9, w8, w1
0x1096b0008(+8):		stlxr	w10, w9, [x0]
0x1096b000c(+12):		cbnz	w10, #-12
0x1096b0010(+16):		mov	x0, x8
0x1096b0014(+20):		ret
22
atomicrmw.t:91:         terra atomic_fadd(x : &double,y : double) : {}
atomicrmw.t:92:             atomicrmw("fadd", x, y, { syncscope = "", ordering = "monotonic", align = native, isvolatile = false })
atomicrmw.t:91:         end
definition 	{&double,double} -> {}
define dso_local void @"$atomic_fadd"(double* %0, double %1) {
entry:
  %2 = atomicrmw fadd double* %0, double %1 monotonic, align 8
  ret void
}
assembly for function at address 0x1096b8000
0x1096b8000(+0):		ldr	d1, [x0]
0x1096b8004(+4):		b	#16
0x1096b8008(+8):		fmov	d1, x10
0x1096b800c(+12):		cmp	x10, x9
0x1096b8010(+16):		b.eq	#40
0x1096b8014(+20):		fadd	d2, d1, d0
0x1096b8018(+24):		fmov	x8, d2
0x1096b801c(+28):		fmov	x9, d1
0x1096b8020(+32):		ldaxr	x10, [x0]
0x1096b8024(+36):		cmp	x10, x9
0x1096b8028(+40):		b.ne	#-32
0x1096b802c(+44):		stlxr	wzr, x8, [x0]
0x1096b8030(+48):		cbnz	wzr, #-16
0x1096b8034(+52):		b	#-44
0x1096b8038(+56):		ret
21
atomicrmw.t:69:         terra atomic_add_and_return(x : &int32,y : int32) : int32
atomicrmw.t:70:             return atomicrmw("add", x, y, { syncscope = "", ordering = "acq_rel", align = native, isvolatile = false })
atomicrmw.t:69:         end
definition 	{&int32,int32} -> int32
define dso_local i32 @"$atomic_add_and_return"(i32* %0, i32 %1) {
entry:
  %2 = atomicrmw add i32* %0, i32 %1 acq_rel, align 4
  ret i32 %2
}
assembly for function at address 0x1096b0000
0x1096b0000(+0):		ldaxr	w8, [x0]
0x1096b0004(+4):		add	w9, w8, w1
0x1096b0008(+8):		stlxr	w10, w9, [x0]
0x1096b000c(+12):		cbnz	w10, #-12
0x1096b0010(+16):		mov	x0, x8
0x1096b0014(+20):		ret
LLVM ERROR: Cannot select: intrinsic %llvm.aarch64.stlxr
zsh: abort      ../build/bin/terra atomicrmw.t
```

**Comment by elliottslaughter** [comment] 2022-08-23 19:08
Can you confirm that this reduced test reproduces the issue?

```terra
terra atomic_add_and_return(x : &int, y : int)
  return terralib.atomicrmw("add", x, y, {ordering = "acq_rel"})
end
atomic_add_and_return:printpretty(false)
atomic_add_and_return:disas()

terra add_and_return()
  var i : int = 1

  var r = atomic_add_and_return(&i, 20)

  return r + i
end

print(add_and_return())
assert(add_and_return() == 22)
```

**Comment by elliottslaughter** [comment] 2022-08-23 19:58
What about this?

```
terra atomic_fadd(x : &double, y : double)
  terralib.atomicrmw("fadd", x, y, {ordering = "monotonic"})
end
atomic_fadd:printpretty(false)
atomic_fadd:disas()

terra fadd()
  var f : double = 1.0

  atomic_fadd(&f, 20.0)

  return f
end

print(fadd())
assert(fadd() == 21.0)
```

**Comment by elliottslaughter** [comment] 2022-08-23 20:37
Ok, there's a typo in the test. That explains why I'm so confused.

Try this one:

```terra
terra atomic_xchg_pointer(x : &&int, y : &int)
  return terralib.atomicrmw("xchg", x, y, {ordering = "acq_rel"})
end
atomic_xchg_pointer:printpretty(false)
atomic_xchg_pointer:disas()

terra xchg_pointer()
  var i : int = 1
  var j : int = 20
  var k = &i

  var r = atomic_xchg_pointer(&k, &j)

  return r == &i and k == &j
end

print(xchg_pointer())
assert(xchg_pointer())
```

**Comment by elliottslaughter** [comment] 2022-08-23 22:39
Let's try running this code through Clang. This is as close as I can get to the equivalent C code, and if it works maybe we can teach Terra to emit the equivalent LLVM IR.

`bug603.c`:

```c
#include <assert.h>

int *atomic_xchg_pointer(int **x, int *y) {
  int *result;
  __atomic_exchange(x, &y, &result, __ATOMIC_ACQ_REL);
  return result;
}

int xchg_pointer() {
  int i = 1;
  int j = 20;
  int *k = &i;

  int *r = atomic_xchg_pointer(&k, &j);

  return r == &i && k == &j;
}

int main() {
  assert(xchg_pointer());
  return 0;
}
```

```
clang bug603.c -o bug603 -Wall
./bug603
clang bug603.c -o bug603.ll -S -emit-llvm -Wall
```

And attach the final `.ll` file here so we can see what Clang is generating (assuming it compiles at all).

**Comment by elliottslaughter** [comment] 2022-08-23 22:43
Also please run this through Terra and let's see what Terra is generating:

`bug603.t`:

```terra
terra atomic_xchg_pointer(x : &&int, y : &int)
  return terralib.atomicrmw("xchg", x, y, {ordering = "acq_rel"})
end

terra xchg_pointer()
  var i : int = 1
  var j : int = 20
  var k = &i

  var r = atomic_xchg_pointer(&k, &j)

  return r == &i and k == &j
end
print(terralib.saveobj(nil, "llvmir", {xchg_pointer=xchg_pointer}, nil, nil, false))

print(xchg_pointer())
assert(xchg_pointer())
```

**Comment by elliottslaughter** [comment] 2022-09-02 17:38
I was playing with this again, and I noticed that running the LLVM IR through `llc` results in this error:

```
llc: error: .../llc: bug603t_x86.ll:48:33: error: atomicrmw xchg operand must be an integer or floating point type
  %4 = atomicrmw xchg i32** %2, i32* %3 acq_rel, align 8
                                ^
```

This seems inconsistent with the [documentation](https://llvm.org/docs/LangRef.html#atomicrmw-instruction), but I guess the documentation is just wrong. Oh well.

I'll put in a change to disallow pointers in `xchg` since it is apparently not supported by LLVM.

**Comment by elliottslaughter** [comment] 2022-09-02 18:11
@shoe42 Can you try again on master? I think all of these bugs should be fixed or worked around at this point.

**Closed as completed** 2022-09-02 19:01 UTC
