### ISSUE TITLE
Failed to initialize target for LLVM Triple

### ISSUE THREAD

**Issue by cata0309** [terralang/terra#514] opened 2021-10-13 12:56 UTC
I compiled commit: https://github.com/terralang/terra/commit/a337b4fd12c84c3dc802803f566d7607a2195c56
The compilation went fine. When running `terra`
```
$ ./terra
src/terralib.lua:750: failed to initialize target for LLVM Triple: nvptx64-nvidia-cuda (No available targets are compatible with triple "nvptx64-nvidia-cuda")
```
Do you have any idea on why is this happening or how can this be fixed?
LLVM version 12.0.1
Thanks.

**Comment by elliottslaughter** [comment] 2021-10-13 18:20
It looks like you built your LLVM without the NVPTX target enabled. Terra currently requires that LLVM be built (at least) with the native target (X86, etc., depending on platform) and NVPTX (i.e., CUDA).

The easiest way to do this is to build LLVM with all targets enabled. You can see a sample recipe for doing this here: https://github.com/terralang/terra#instructions-for-building-llvm-from-source

**Comment by cata0309** [comment] 2021-12-20 20:33
Are there any plains to remove NVPTX dependency(make it optional)?

**Comment by elliottslaughter** [comment] 2021-12-24 17:51
Yes, we should only do this when Terra itself is built with CUDA.

I'm marking this as a duplicate of #446, if there is anything else please let us know there or open a new issue (if it's something unrelated).

**Closed by elliottslaughter** 2021-12-24 17:51 UTC
